---
- name: "Update du cache"
  apt:
   update_cache: yes

- name: "Installation php7.4"
  apt:
   name: php7.4
   state: present

- name: "Installation fonctions php"
  apt:
   name :  "{{ item  }}"
   state: present
  with_items: "{{ php_packages }}"

- name: "Modif fichier php.ini"
  lineinfile:
   path: /etc/php/7.4/fpm/php.ini
   regexp: "{{ item.key }}"
   line: "{{ item.key }} = {{ item.value }}"
  with_items: "{{ php_ini }}"

