---
# tasks file for user

- name: "create group"
  group:
   name: "{{ user }}"
   state: present

- name: "create user"
  user:
   name: "{{ user }}"
   create_home: 1
   shell: /usr/bin/zsh
   comment: mon user
   #uid: 2000
   group: "{{ user }}"

- name : "ssh key"
  authorized_key:
   user: "{{ user }}"
   state: present
   key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name : "config sudo"
  template:
   src: /etc/ansible/roles/user/templates/sudoers.j2
   dest: /etc/sudoers.d/{{ user }}

