---

- name: "kubeInit for Master"
  hosts: 3.9.177.230 
  remote_user: ubuntu
  become : 1
  tasks:
  - name: "creation fichier daemon.json" 
    lineinfile:
     state: present
     create: yes 
     path: /etc/docker/daemon.json
     line : '{"exec-opts": ["native.cgroupdriver=systemd"]}'

  - name : restart des services
    ansible.builtin.systemd:
     state: restarted
     daemon_reload: yes
     name: "{{ item }}"
    with_items:
     - docker
     - kubelet

  - name: init master 
    shell: "kubeadm init --apiserver-advertise-address=3.9.177.230 --pod-network-cidr=10.244.0.0/16"

  - name: Get the token for joining the worker nodes
    shell: kubeadm token create  --print-join-command
    register: kubernetes_join_command 


  - name: Copy join command to local file
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
