---
# tasks file for mediawiki

- name: "installation prerequis serveur Lamp"
  include: lamp.yml

- name: "installation mediawiki"
  apt:
   name : mediawiki
   state: present

- name: "Ajout du lien symbolique"
  file:
   src: /var/lib/mediawiki
   dest: /var/www/mediawiki 
   state: link

- name : "Mediawiki"
  include: mediawiki.yml
